-- Databricks notebook source
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {
      "byteLimit": 104857600,
      "rowLimit": 1000
     },
     "inputWidgets": {},
     "nuid": "2ce495b3-0b48-4944-ac8f-2ab47c09ed5d",
     "showTitle": false,
     "tableResultSettingsMap": {},
     "title": ""
    }
   },
   "outputs": [],
   "source": [
    "CREATE OR REPLACE VIEW gold.analistas.vw_superset_paretodedefeitosmanaus AS (\n",
    "\n",
    "-- ==============================================================================\n",
    "-- PARETO DE DEFEITOS MANAUS - GRÃO GRANULAR (1 LINHA POR EVENTO)\n",
    "-- Padrão idêntico à vw_superset_paretodedefeitoscontagem\n",
    "-- Dimensões Pareto: CAUSA, AÇÃO, ORIGEM FORNECEDOR\n",
    "-- Fonte: fato_motivo_reparo_producao (cabeçalho) + fato_reparo_produto (detalhe)\n",
    "-- ==============================================================================\n",
    "WITH \n",
    "\n",
    "-- 1. Base granular com normalização UPPER(TRIM) nas dimensões Pareto\n",
    "BASE AS (\n",
    "    SELECT\n",
    "        m.NroLancamento,\n",
    "        m.OrdemProducao                                     AS OP,\n",
    "        m.CodProdutoAcabado                                 AS CodProd_PA,\n",
    "        pa.DescricaoProduto                                 AS Descricao_PA,\n",
    "        CASE WHEN pa.Marca = 'PADRAO' THEN 'HQ' ELSE pa.Marca END AS Fornecedor_PA,\n",
    "        m.SeriePA                                           AS SerieProdutoAcabado,\n",
    "        CAST(m.DataEntradaReparo AS DATE)                   AS DataReparo,\n",
    "        YEAR(m.DataEntradaReparo)                           AS Ano,\n",
    "        MONTH(m.DataEntradaReparo)                          AS Mes,\n",
    "        WEEKOFYEAR(m.DataEntradaReparo)                     AS Semana,\n",
    "        m.DataEntradaReparo,\n",
    "        m.DataFimReparo,\n",
    "        COALESCE(NULLIF(TRIM(m.Defeito), ''), 'Não Informado') AS Defeito,\n",
    "        rp.NroLancamentoProduto,\n",
    "        rp.CodProduto                                       AS CodProd_Componente,\n",
    "        comp.DescricaoProduto                               AS Descricao_Componente,\n",
    "        COALESCE(NULLIF(UPPER(TRIM(rp.Causa)), ''), 'NÃO INFORMADO')            AS Causa,\n",
    "        COALESCE(NULLIF(UPPER(TRIM(rp.Acao)), ''), 'NÃO INFORMADO')             AS Acao,\n",
    "        CASE WHEN rp.SerieProdutoMP <> 'N/A' THEN rp.SerieProdutoMP ELSE NULL END AS Serie_Componente_Antigo,\n",
    "        CASE WHEN rp.SerieProdutoNovaMP <> 'N/A' THEN rp.SerieProdutoNovaMP ELSE NULL END AS Serie_Componente_Novo,\n",
    "        COALESCE(NULLIF(UPPER(TRIM(rp.OrigemFornecedor)), ''), 'NÃO INFORMADO') AS OrigemFornecedor,\n",
    "        'MANAUS/AM'                                         AS Planta,\n",
    "        'TV'                                                AS Familia,\n",
    "        1                                                   AS Qtd_Defeitos\n",
    "    FROM gold.sankhyaind.fato_motivo_reparo_producao m\n",
    "    LEFT JOIN gold.sankhyaind.fato_reparo_produto rp ON m.NroLancamento = rp.NroLancamento\n",
    "    LEFT JOIN gold.sankhyaind.dim_produtos pa ON m.CodProdutoAcabado = pa.CodProduto\n",
    "    LEFT JOIN gold.sankhyaind.dim_produtos comp ON rp.CodProduto = comp.CodProduto\n",
    "    WHERE m.DataEntradaReparo IS NOT NULL\n",
    "),\n",
    "\n",
    "-- 2. Rankings DINÂMICOS por dimensão (calculados sobre volume real)\n",
    "-- ===== PARETO POR CAUSA =====\n",
    "AGREGADO_CAUSA AS (\n",
    "    SELECT Ano, Mes, Causa, SUM(Qtd_Defeitos) AS Total_Causa\n",
    "    FROM BASE\n",
    "    GROUP BY Ano, Mes, Causa\n",
    "),\n",
    "PARETO_CAUSA AS (\n",
    "    SELECT\n",
    "        Ano,\n",
    "        Mes,\n",
    "        Causa,\n",
    "        ROW_NUMBER() OVER (PARTITION BY Ano, Mes ORDER BY Total_Causa DESC, Causa ASC) AS Rank_Causa,\n",
    "        SUM(Total_Causa) OVER (\n",
    "            PARTITION BY Ano, Mes ORDER BY Total_Causa DESC, Causa ASC\n",
    "            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n",
    "        ) / SUM(Total_Causa) OVER (PARTITION BY Ano, Mes) AS Pareto_Causa_Pct\n",
    "    FROM AGREGADO_CAUSA\n",
    "),\n",
    "\n",
    "-- ===== PARETO POR AÇÃO =====\n",
    "AGREGADO_ACAO AS (\n",
    "    SELECT Ano, Mes, Acao, SUM(Qtd_Defeitos) AS Total_Acao\n",
    "    FROM BASE\n",
    "    GROUP BY Ano, Mes, Acao\n",
    "),\n",
    "PARETO_ACAO AS (\n",
    "    SELECT\n",
    "        Ano,\n",
    "        Mes,\n",
    "        Acao,\n",
    "        ROW_NUMBER() OVER (PARTITION BY Ano, Mes ORDER BY Total_Acao DESC, Acao ASC) AS Rank_Acao,\n",
    "        SUM(Total_Acao) OVER (\n",
    "            PARTITION BY Ano, Mes ORDER BY Total_Acao DESC, Acao ASC\n",
    "            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n",
    "        ) / SUM(Total_Acao) OVER (PARTITION BY Ano, Mes) AS Pareto_Acao_Pct\n",
    "    FROM AGREGADO_ACAO\n",
    "),\n",
    "\n",
    "-- ===== PARETO POR ORIGEM FORNECEDOR =====\n",
    "AGREGADO_ORIGEM AS (\n",
    "    SELECT Ano, Mes, OrigemFornecedor, SUM(Qtd_Defeitos) AS Total_Origem\n",
    "    FROM BASE\n",
    "    GROUP BY Ano, Mes, OrigemFornecedor\n",
    "),\n",
    "PARETO_ORIGEM AS (\n",
    "    SELECT\n",
    "        Ano,\n",
    "        Mes,\n",
    "        OrigemFornecedor,\n",
    "        ROW_NUMBER() OVER (PARTITION BY Ano, Mes ORDER BY Total_Origem DESC, OrigemFornecedor ASC) AS Rank_Origem,\n",
    "        SUM(Total_Origem) OVER (\n",
    "            PARTITION BY Ano, Mes ORDER BY Total_Origem DESC, OrigemFornecedor ASC\n",
    "            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n",
    "        ) / SUM(Total_Origem) OVER (PARTITION BY Ano, Mes) AS Pareto_Origem_Pct\n",
    "    FROM AGREGADO_ORIGEM\n",
    "),\n",
    "\n",
    "-- ===== PRODUÇÃO AGREGADA POR PRODUTO/MÊS =====\n",
    "PRODUCAO AS (\n",
    "    SELECT CodProd, Ano, Mes, SUM(Qtd_Produzida) AS Qtd_Produzida\n",
    "    FROM gold.analistas.vw_producaomanaus\n",
    "    GROUP BY CodProd, Ano, Mes\n",
    "),\n",
    "\n",
    "-- ===== EXPEDIÇÃO AGREGADA POR PRODUTO/MÊS =====\n",
    "EXPEDIDO AS (\n",
    "    SELECT CodProd, Ano, Mes, SUM(Quantidade) AS QtdExpedida\n",
    "    FROM gold.analistas.vw_superset_expedicaoconsolidada\n",
    "    WHERE Planta = 'MANAUS/AM'\n",
    "    GROUP BY CodProd, Ano, Mes\n",
    ")\n",
    "\n",
    "-- 3. Projeção Final — ranking reflete o volume real do dataset filtrado\n",
    "SELECT\n",
    "    r.Planta,\n",
    "    r.NroLancamento,\n",
    "    r.OP,\n",
    "    r.Ano,\n",
    "    r.Mes,\n",
    "    r.Semana,\n",
    "    r.DataReparo,\n",
    "    r.DataEntradaReparo,\n",
    "    r.DataFimReparo,\n",
    "\n",
    "    CASE r.Mes\n",
    "        WHEN 1  THEN '01. JANEIRO'   WHEN 2  THEN '02. FEVEREIRO'\n",
    "        WHEN 3  THEN '03. MARÇO'     WHEN 4  THEN '04. ABRIL'\n",
    "        WHEN 5  THEN '05. MAIO'      WHEN 6  THEN '06. JUNHO'\n",
    "        WHEN 7  THEN '07. JULHO'     WHEN 8  THEN '08. AGOSTO'\n",
    "        WHEN 9  THEN '09. SETEMBRO'  WHEN 10 THEN '10. OUTUBRO'\n",
    "        WHEN 11 THEN '11. NOVEMBRO'  WHEN 12 THEN '12. DEZEMBRO'\n",
    "    END AS Mes_Ordenado,\n",
    "\n",
    "    r.CodProd_PA,\n",
    "    r.Descricao_PA,\n",
    "    r.Fornecedor_PA,\n",
    "    r.Familia,\n",
    "    r.SerieProdutoAcabado,\n",
    "\n",
    "    r.Defeito,\n",
    "    r.CodProd_Componente,\n",
    "    r.Descricao_Componente,\n",
    "    r.Causa,\n",
    "    r.Acao,\n",
    "    r.OrigemFornecedor,\n",
    "    r.Serie_Componente_Antigo,\n",
    "    r.Serie_Componente_Novo,\n",
    "\n",
    "    r.Qtd_Defeitos,\n",
    "\n",
    "    -- Métricas de volume (produção e expedição do produto/mês) — 1 valor por SKU/Mês (ROW_NUMBER anti-exploit, sem OP)\n",
    "    CASE WHEN ROW_NUMBER() OVER (PARTITION BY r.CodProd_PA, r.Ano, r.Mes ORDER BY r.NroLancamento) = 1\n",
    "         THEN COALESCE(prod.Qtd_Produzida, 0) ELSE 0 END AS Qtd_Produzida,\n",
    "    CASE WHEN ROW_NUMBER() OVER (PARTITION BY r.CodProd_PA, r.Ano, r.Mes ORDER BY r.NroLancamento) = 1\n",
    "         THEN COALESCE(exp.QtdExpedida, 0) ELSE 0 END AS QtdExpedida,\n",
    "\n",
    "    -- Métricas do Pareto (calculadas sobre dados filtrados)\n",
    "    pc.Pareto_Causa_Pct,\n",
    "    pa.Pareto_Acao_Pct,\n",
    "    po.Pareto_Origem_Pct,\n",
    "\n",
    "    -- Top 10 dinâmico (baseado no volume real pós-filtro)\n",
    "    CASE WHEN pc.Rank_Causa  <= 10 THEN LPAD(CAST(pc.Rank_Causa AS STRING), 2, '0') || '. ' || r.Causa           ELSE '11. OUTROS' END AS Causa_Top10,\n",
    "    CASE WHEN pa.Rank_Acao   <= 10 THEN LPAD(CAST(pa.Rank_Acao AS STRING), 2, '0')  || '. ' || r.Acao            ELSE '11. OUTROS' END AS Acao_Top10,\n",
    "    CASE WHEN po.Rank_Origem <= 10 THEN LPAD(CAST(po.Rank_Origem AS STRING), 2, '0') || '. ' || r.OrigemFornecedor ELSE '11. OUTROS' END AS OrigemFornecedor_Top10,\n",
    "\n",
    "    -- Colunas traduzidas para inglês em UPPER (fallback = valor PT original já UPPER)\n",
    "    UPPER(COALESCE(trad_causa.valor_en, r.Causa))              AS Causa_EN,\n",
    "    UPPER(COALESCE(trad_acao.valor_en, r.Acao))                AS Acao_EN,\n",
    "    UPPER(COALESCE(trad_origem.valor_en, r.OrigemFornecedor))  AS OrigemFornecedor_EN,\n",
    "\n",
    "    -- Rótulo prefixado para ECharts — respeita a ordem real de volume\n",
    "    LPAD(CAST(pc.Rank_Causa AS STRING), 2, '0')  || '. ' || r.Causa            AS Causa_Ordenada,\n",
    "    LPAD(CAST(pa.Rank_Acao AS STRING), 2, '0')   || '. ' || r.Acao             AS Acao_Ordenada,\n",
    "    LPAD(CAST(po.Rank_Origem AS STRING), 2, '0') || '. ' || r.OrigemFornecedor AS OrigemFornecedor_Ordenado,\n",
    "\n",
    "    -- Top 10 EN (para gráficos do relatório em inglês) — UPPER\n",
    "    CASE WHEN pc.Rank_Causa  <= 10 THEN LPAD(CAST(pc.Rank_Causa AS STRING), 2, '0') || '. ' || UPPER(COALESCE(trad_causa.valor_en, r.Causa))           ELSE '11. OTHERS' END AS Causa_Top10_EN,\n",
    "    CASE WHEN pa.Rank_Acao   <= 10 THEN LPAD(CAST(pa.Rank_Acao AS STRING), 2, '0')  || '. ' || UPPER(COALESCE(trad_acao.valor_en, r.Acao))            ELSE '11. OTHERS' END AS Acao_Top10_EN,\n",
    "    CASE WHEN po.Rank_Origem <= 10 THEN LPAD(CAST(po.Rank_Origem AS STRING), 2, '0') || '. ' || UPPER(COALESCE(trad_origem.valor_en, r.OrigemFornecedor)) ELSE '11. OTHERS' END AS OrigemFornecedor_Top10_EN,\n",
    "\n",
    "    -- Rótulos ECharts EN — UPPER\n",
    "    LPAD(CAST(pc.Rank_Causa AS STRING), 2, '0')  || '. ' || UPPER(COALESCE(trad_causa.valor_en, r.Causa))            AS Causa_Ordenada_EN,\n",
    "    LPAD(CAST(pa.Rank_Acao AS STRING), 2, '0')   || '. ' || UPPER(COALESCE(trad_acao.valor_en, r.Acao))             AS Acao_Ordenada_EN,\n",
    "    LPAD(CAST(po.Rank_Origem AS STRING), 2, '0') || '. ' || UPPER(COALESCE(trad_origem.valor_en, r.OrigemFornecedor)) AS OrigemFornecedor_Ordenado_EN\n",
    "\n",
    "FROM BASE r\n",
    "LEFT JOIN PARETO_CAUSA  pc ON r.Ano = pc.Ano AND r.Mes = pc.Mes AND r.Causa           = pc.Causa\n",
    "LEFT JOIN PARETO_ACAO   pa ON r.Ano = pa.Ano AND r.Mes = pa.Mes AND r.Acao            = pa.Acao\n",
    "LEFT JOIN PARETO_ORIGEM po ON r.Ano = po.Ano AND r.Mes = po.Mes AND r.OrigemFornecedor = po.OrigemFornecedor\n",
    "-- JOINs de tradução PT → EN\n",
    "LEFT JOIN gold.analistas.tb_traducao_paretodedefeitosmanaus trad_causa\n",
    "    ON trad_causa.campo = 'CAUSA' AND trad_causa.valor_pt = r.Causa\n",
    "LEFT JOIN gold.analistas.tb_traducao_paretodedefeitosmanaus trad_acao\n",
    "    ON trad_acao.campo = 'ACAO' AND trad_acao.valor_pt = r.Acao\n",
    "LEFT JOIN gold.analistas.tb_traducao_paretodedefeitosmanaus trad_origem\n",
    "    ON trad_origem.campo = 'ORIGEM_FORNECEDOR' AND trad_origem.valor_pt = r.OrigemFornecedor\n",
    "-- JOINs de volume (produção + expedição)\n",
    "LEFT JOIN PRODUCAO prod ON r.CodProd_PA = prod.CodProd AND r.Ano = prod.Ano AND r.Mes = prod.Mes\n",
    "LEFT JOIN EXPEDIDO exp  ON r.CodProd_PA = exp.CodProd  AND r.Ano = exp.Ano  AND r.Mes = exp.Mes\n",
    "ORDER BY r.DataReparo DESC\n",
    ");"
   ]
  }
 ],
 "metadata": {
  "application/vnd.databricks.v1+notebook": {
   "computePreferences": null,
   "dashboards": [],
   "environmentMetadata": null,
   "inputWidgetPreferences": null,
   "language": "sql",
   "notebookMetadata": {
    "pythonIndentUnit": 4,
    "sqlQueryOptions": {
     "applyAutoLimit": true,
     "catalog": "databricks_belmicro_55797217030344",
     "schema": "default"
    }
   },
   "notebookName": "vw_superset_paretodedefeitosmanaus.dbquery.ipynb",
   "widgets": {}
  },
  "language_info": {
   "name": "sql"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}