version: '3.8'

services:
  vetra-platform:
    build: .
    container_name: vetra_consultive_agent
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped