name: Vetra IA de Análise de Dados

on:
  push:
    branches: [ "main", "feature/repo-restructure" ]
  pull_request:
    branches: [ "main", "feature/repo-restructure" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v4

    - name: Configurar Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Testar Build da Imagem Docker
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: vetra-agent:latest