CREATE OR REPLACE VIEW vw_SMT_ResumoPerformance AS
SELECT 
    chave_ano AS ANO,
    COUNT(*) AS QTD_TOTAL,
    SUM(CASE WHEN origem = 'PRODUÇÃO' THEN 1 ELSE 0 END) AS 'QTD PRODUÇÃO',
    SUM(CASE WHEN origem = 'ASSISTÊNCIA' THEN 1 ELSE 0 END) AS 'QTD ASSISTÊNCIA',
    SUM(CASE WHEN origem = 'SMT' THEN 1 ELSE 0 END) AS 'QTD SMT',
    COUNT(DISTINCT tecnico) AS 'TÉCNICOS',
    ROUND(COUNT(*) / NULLIF(COUNT(DISTINCT tecnico), 0), 0) AS 'MÉDIA POR TÉCNICO',
    ROUND((SUM(CASE WHEN origem = 'PRODUÇÃO' THEN 1 ELSE 0 END) / COUNT(*)) * 100, 2) AS '% PRODUÇÃO',
    ROUND((SUM(CASE WHEN origem = 'ASSISTÊNCIA' THEN 1 ELSE 0 END) / COUNT(*)) * 100, 2) AS '% ASSISTÊNCIA',
    ROUND((SUM(CASE WHEN origem = 'SMT' THEN 1 ELSE 0 END) / COUNT(*)) * 100, 2) AS '% SMT'
FROM staging_reparos
GROUP BY chave_ano;